name: Build on every push and every pull-request

on:
  pull_request:
    paths-ignore:
      - "*.md"
  push:
    paths-ignore:
      - "*.md"
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            rust-targets: x86_64-apple-darwin
            args: "--target universal-apple-darwin"
            artifact-name: build-macos-universal
          - platform: ubuntu-latest
            rust-targets: ""
            args: ""
            artifact-name: build-linux-x86_64
          - platform: ubuntu-24.04-arm
            rust-targets: ""
            args: ""
            artifact-name: build-linux-arm64
          - platform: windows-latest
            rust-targets: ""
            args: ""
            artifact-name: build-windows-x86_64
          - platform: windows-11-arm
            rust-targets: ""
            args: ""
            artifact-name: build-windows-arm64
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install dependencies (ubuntu only)
        if: startsWith(matrix.platform, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.rust-targets }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"

      - name: Install frontend dependencies
        run: npm install

      - name: Build the app and release
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "Launcher v__VERSION__"
          releaseBody: "See the assets to download and install this version."
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}

      - name: Build the app
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ${{ matrix.args }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: |
            src-tauri/target/release/bundle/nsis/*.exe
            src-tauri/target/release/bundle/msi/*.msi
            src-tauri/target/release/bundle/appimage/*.AppImage
            src-tauri/target/release/bundle/deb/*.deb
            src-tauri/target/release/bundle/rpm/*.rpm
            src-tauri/target/release/bundle/dmg/*.dmg
            src-tauri/target/release/bundle/macos/*.app
            src-tauri/target/universal-apple-darwin/release/bundle/dmg/*.dmg
            src-tauri/target/universal-apple-darwin/release/bundle/macos/*.app
